# Generated by Django 5.0.2 on 2025-03-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_animal_category_alter_animal_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
