# Generated by Django 5.0.2 on 2025-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_animal_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('air', 'Air'), ('water', 'Water'), ('land', 'Land')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
