# Generated by Django 5.0.2 on 2025-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_animal_category_alter_animal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AddField(
            model_name='animal',
            name='audio_description',
            field=models.CharField(blank=True, help_text='Description of the audio sound', max_length=200),
        ),
        migrations.AddField(
            model_name='animal',
            name='behavior_info',
            field=models.TextField(blank=True, help_text='Behavioral characteristics'),
        ),
        migrations.AddField(
            model_name='animal',
            name='conservation_status',
            field=models.TextField(blank=True, help_text='Conservation status and threats'),
        ),
        migrations.AddField(
            model_name='animal',
            name='fun_facts_kids',
            field=models.TextField(blank=True, help_text='Fun and interesting facts for kids'),
        ),
        migrations.AddField(
            model_name='animal',
            name='habitat_info',
            field=models.TextField(blank=True, help_text='Detailed habitat information'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='animal_sounds/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description_adults',
            field=models.TextField(help_text='Scholarly description with scientific information'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description_kids',
            field=models.TextField(help_text='Kid-friendly description (3rd-4th grade level)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='section',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Scholars', 'Scholars')], max_length=10),
        ),
    ]
