# Generated by Django 5.0.2 on 2025-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_animal_options_animal_audio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('air', 'Air'), ('water', 'Water'), ('land', 'Land')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description_adults',
            field=models.TextField(blank=True, help_text='Scholarly description with scientific information'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description_kids',
            field=models.TextField(blank=True, help_text='Kid-friendly description (3rd-4th grade level)'),
        ),
    ]
