# Generated by Django 5.1.7 on 2025-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_quiz_alter_animal_options_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('flying', 'Flying Animals'), ('land', 'Land Animals'), ('water', 'Water Animals')], max_length=20)),
                ('image', models.ImageField(upload_to='category_images/')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
