# Generated by Django 5.1.7 on 2025-03-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_animalcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='animalcategory',
            name='section',
            field=models.CharField(default='scholars', max_length=20),
        ),
        migrations.AlterField(
            model_name='animalcategory',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
